instance:
    domain: fchan.xyz
    port: 3000
    protocol: https
    name: FChan
    summary: FChan is a federated image board instance.
    ## add your instance salt here for secure tripcodes
    salt: ""
    filesize_limit: 8

## For `Protocol` if you plan to support https
## make sure you setup the ssl certs before running the server initially
## do not start with `http` and then switch to `https`
## this will cause issues if switched from on protocol to the other.
## If you do, the database entries will have to be converted to support the change
## this will cause a lot of headaches if switched back and forth.
## Choose which one you are going to support and do not change it for best results.

email:
    address: ""
    password: ""
    host: localhost
    port: 587
    notify: []
database:
    host: localhost
    port: 5432
    name: postgres
    user: postgres
    password: hackme

## enter proxy ip and port if you want to have tor connections supported
tor_proxy: 127.0.0.1:9050
cookie_key: ""
auth_req:
    - captcha
    - Email
    - passphrase
posts_per_page: 10
supported_files:
    - image/gif
    - image/jpeg
    - image/png
    - image/webp
    - image/apng
    - video/mp4
    - video/ogg
    - video/webm
    - audio/mpeg
    - audio/ogg
    - audio/wav
    - audio/wave
    - audio/x-wav

## this is the key used to access moderation pages leave empty to randomly generate each restart
## share with other admin or jannies if you are having others to moderate
mod_key: ""
