version: '3.9'
services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: hackme
    expose:
    - 5432
    volumes:
      - ./pgdata/:/var/lib/postgresql/data/
  app:
    build: ./
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./public/:/app/public/
      - ./pem/:/app/pem/
      - ./static/:/app/static/
    environment:
      INSTANCE_DOMAIN: localhost
      INSTANCE_PROTOCOL: https
      INSTANCE_NAME: FChan
      INSTANCE_FILESIZE_LIMIT: 8

      COOKIE_KEY: ""

      DB_HOST: db
      DB_PASS: hackme
    ports:
      - 3000:3000
